version: '3'
services:
   redis:
     image: redis:latest
     restart: always
     container_name: redis
     ports:
       - "6379:6379"
     privileged: true
     volumes:
       - ./redis.conf:/etc/redis/redis.conf 
       - ./data:/data      
       - ./data/redis.log:/var/log/redis.log
     command: redis-server /etc/redis/redis.conf 