version: '3'
services:
  centos-ssh:
    container_name: centos
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "2222:22"
    user: root
    privileged: true
    tty: true
    restart: always
    network_mode: bridge
