version: '3'
services:
  ubuntu-20.04:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: singleNode
    user: root
    privileged: true
    tty: true
    restart: always
    network_mode: bridge
