version: '3'
services:
  mysql:
    restart: always
    image: mysql:5.7.18
    container_name: mysql-lable
    volumes:
      - ./data:/var/lib/mysql
      - ./conf/my.cnf:/etc/my.cnf
    environment:
      - "MYSQL_ROOT_PASSWORD=mysql57"
      - "MYSQL_DATABASE=testenv"
      - "TZ=Asia/Shanghai"
    ports:
      - 3306:3306