version: "3"
services:
  nginx:
    container_name: nginx
    image: nginx:latest
    restart: always
    privileged: true
    ports:
      - "8080:80"
      - "8000:8095"
    volumes:
      - ./conf/nginx.conf:/etc/nginx/nginx.conf
      - ./conf/conf.d:/etc/nginx/conf.d
      - ./log:/var/log/nginx
      - ./frontend:/usr/share/nginx/html
     
