version: "3"
services:
  wordpress-mysql:
    container_name: mysql
    image: mysql:latest
    command:
    - --default_authentication_plugin=mysql_native_password
    - --character-set-server=utf8mb4
    - --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./database/mysql/:/var/lib/mysql/
      - ./database/my.cnf:/etc/my.cnf
    restart: always
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_ROOT_PASSWORD: docker233
    privileged: true
  
  wordpress:
    container_name: wordpress
    depends_on:
      - wordpress-mysql
    image: wordpress:latest
    ports:
      - "8000:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: wordpress-mysql:3306
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: docker233
    privileged: true
    volumes:
      - ./wordpress-settings/:/usr/src/wordpress/
     