version: '3'

services:
  jenkins:
   image: jenkins/jenkins
   container_name: jenkins
   volumes:    
    - ./data/jenkins/:/var/jenkins_home
   ports: 
    - "8080:8080"
   expose:
    - "8080"
    - "50000"
   privileged: true
   user: root
   restart: always
   environment:
    JAVA_OPTS: '-Djava.util.logging.config.file=/var/jenkins_home/log.properties'
