version: '3'
services:
  ubuntu-12.04:
    build: 
      context: .
      dockerfile: ./12.04/Dockerfile
    container_name: node1204
    user: root
    privileged: true
    tty: true
    restart: always
    network_mode: bridge

  ubuntu-18.04:
    build:
      context: .
      dockerfile: ./18.04/Dockerfile
    container_name: node1804
    user: root
    privileged: true
    tty: true
    restart: always
    network_mode: bridge

  ubuntu-20.04:
    build:
      context: .
      dockerfile: ./20.04/Dockerfile
    container_name: node2004
    user: root
    privileged: true
    tty: true
    restart: always
    network_mode: bridge
